name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} / ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-latest(24.04.2)の場合、puppeteerのバージョンの関係でe2eテストに失敗してしまうため、ubuntuを一旦22.04にダウングレード
        os: [ubuntu-22.04, windows-latest]
        node: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Run test
        run: |
          npm ci
          npm test
